# Generated by Django 5.1.3 on 2024-12-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisita', models.BooleanField(default=False)),
                ('acesso_cardapio', models.BooleanField(default=False)),
                ('acesso_pagina_inicial', models.BooleanField(default=False)),
                ('acesso_sobre', models.BooleanField(default=False)),
                ('toque_contato', models.BooleanField(default=False)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticasGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessos', models.BigIntegerField(default=0)),
                ('revisitas', models.BigIntegerField(default=0)),
                ('acessos_cardapio', models.BigIntegerField(default=0)),
                ('acessos_pagina_inicial', models.BigIntegerField(default=0)),
                ('acessos_sobre', models.BigIntegerField(default=0)),
                ('toques_link_contato', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='pratos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratos', to='moretti.categoria')),
            ],
        ),
    ]
