# Generated by Django 5.1.3 on 2024-12-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moretti', '0003_cardapiobg_cardapiotexto_iniciobg_iniciotexto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciotexto',
            name='localizacao_link_maps',
        ),
    ]
